### ISSUE TITLE
_ColorHelper build error

### ISSUE THREAD

**Issue by IsaiahPatton** [CodeCrafter47/Rainbow#7]
org.projectrainbow._ColorHelper does not download right, and
_ColorHelper.COLOR_CHAR = '§';
reads as:
_ColorHelper.COLOR_CHAR = 'ยง';

[ERROR] /org/projectrainbow/_ColorHelper.java:[30,35] unclosed character literal
[ERROR] /org/projectrainbow/_ColorHelper.java:[30,37] illegal character: \167
[ERROR] /org/projectrainbow/_ColorHelper.java:[30,38] unclosed character literal

**Comment by CodeCrafter47** [comment]
That's a char set issue on your end. The file is UTF-8 encoded.
